USE alx_book_store;

SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXUMM_LENGTH, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, COLUMN_TYPE 
FROM IFORMATION_SCHEMA.COLUMNS  
WHERE TABLE_NAME = 'Books' AND TABLE_SCHEMA = 'alx_book_store'